/*
* Un pedido puede contener varios productos y un producto puede aparecer en varios pedidos.
* La tabla order_lines resuelve esa relación y guarda además la cantidad y el precio en el momento de la compra.
*/
-- Tabla que almacena los productos disponibles
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    sku VARCHAR(50) NOT NULL,
    price NUMERIC(12, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_products_sku UNIQUE (sku),
    CONSTRAINT chk_products_price_positive CHECK (price > 0),
    CONSTRAINT chk_products_stock_non_negative CHECK (stock >= 0)
);

-- Tabla pedidos
CREATE TABLE orders (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(20) NOT NULL DEFAULT 'CREATED',
                        total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
                        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        CONSTRAINT chk_orders_status
                            CHECK (status IN ('CREATED', 'CONFIRMED', 'CANCELLED')),
                        CONSTRAINT chk_orders_total_non_negative
                            CHECK (total_amount >= 0)
);
/*
 * Tabla intermedia entre pedidos y productos.
 * También almacena la cantidad y el precio del producto
 * en el momento de crear el pedido.
 */
CREATE TABLE order_lines (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id BIGINT NOT NULL,
                             product_id BIGINT NOT NULL,
                             quantity INTEGER NOT NULL,
                             unit_price NUMERIC(12, 2) NOT NULL,
                             subtotal NUMERIC(12, 2) NOT NULL,

                             CONSTRAINT fk_order_lines_order
                                 FOREIGN KEY (order_id)
                                     REFERENCES orders (id)
                                     ON DELETE CASCADE,

                             CONSTRAINT fk_order_lines_product
                                 FOREIGN KEY (product_id)
                                     REFERENCES products (id)
                                     ON DELETE RESTRICT,

                             CONSTRAINT uk_order_lines_order_product
                                 UNIQUE (order_id, product_id),

                             CONSTRAINT chk_order_lines_quantity_positive
                                 CHECK (quantity > 0),

                             CONSTRAINT chk_order_lines_unit_price_positive
                                 CHECK (unit_price > 0),

                             CONSTRAINT chk_order_lines_subtotal_positive
                                 CHECK (subtotal > 0)
);

CREATE INDEX idx_order_lines_order_id
    ON order_lines (order_id);

CREATE INDEX idx_order_lines_product_id
    ON order_lines (product_id);

CREATE INDEX idx_orders_status
    ON orders (status);